# Makefile para projeto Shell Sort Python

.PHONY: clean run

# Variáveis
PYTHON=python3
MAIN=main.py

# Comando padrão: executa o programa
run:
	$(PYTHON) $(MAIN)

# Comando para rodar tudo (pode ser igual a run)
all: run

# Limpa arquivos gerados (outputs)
clean:
	rm -f lineares.txt dinamicas.txt
	rm -rf outsets

